### ISSUE TITLE
fork documentation website to keep it up to date

### ISSUE THREAD

**Issue by shcheklein** [iterative/PyDrive2#22]

**Comment by abubelinha** [comment]
I was going to rise an issue but I guess it would be a duplicate of this.

You mean the project still lacks its own documentation since it just points to the original PyDrive docs, don't you?

----
# Project info:
- Documentation: [Official documentation on GitHub pages](https://gsuitedevs.github.io/PyDrive/docs/build/html/index.html)
----

Which still points to a **PyDrive** site (not PyDrive2)

**Comment by shcheklein** [comment]
> You mean the project still lacks its own documentation since it just points to the original PyDrive docs, don't you?

@abubelinha yes, you got it right!

**Comment by CMiksche** [comment]
The files are already present at the docs folder, so all it takes is for the Repository owner to setup GitHub Pages in settings, or not?!

Btw the current documentation link is broken, I created a PR in the original Repo for that: https://github.com/googleworkspace/PyDrive/pull/209

**Comment by shcheklein** [comment]
I've setup it to run from the `https://iterative.github.io/PyDrive2/docs/build/html/index.html` - but it doesn't work for now. The previous setup was serving it from the `gh-pages` branch. It should be something simple, but requires some additional work. Happy to give you access @CMiksche to take a look at the settings if you want to give it a try.

**Comment by CMiksche** [comment]
> but it doesn't work for now.

It currently seems to work except for the Asset (CSS Style and static JS) part...

Maybe all we need is a ```.nojekyll``` file (which is already in the gh-pages branch) in the master Branch?

I would be happy to look at the settings :-)

**Comment by shcheklein** [comment]
@CMiksche sure! invited you as a maintainer - give it a try please :)

**Comment by shcheklein** [comment]
We forked and updated the docs.
