### ISSUE TITLE
Need example of shared folder access (downloading/listing files/directories)

### ISSUE THREAD

**Issue by pcseanmckay** [iterative/PyDrive2#36]
Trying to create a script to automate the downloading of several terabytes of files from a shared drive folder.  I haven't seen any examples of how to do it.

**Comment by shcheklein** [comment]
I think you can take a look/borrow some code from the DVC code here: https://github.com/iterative/dvc/blob/master/dvc/remote/gdrive.py

Specifically:

1. list files wrapper https://github.com/iterative/dvc/blob/master/dvc/remote/gdrive.py#L430 - takes a query and returns a list of items. In case you need to download a lot of files inside a directory.
2. "'{}' in parents and trashed=false" - https://github.com/iterative/dvc/blob/master/dvc/remote/gdrive.py#L295 - example how to create a query . You can specify a list of directory IDs to list file inside.
3. https://github.com/iterative/dvc/blob/d62a54c7b0fb8bf0f081240d9f578db68b99b3ff/dvc/remote/gdrive.py#L382 - download a file if have an ID of it from the previous call. It's wrapped into tqdm to show the progress bar. Obviously you can simplify in your case.
4. wrap that call into ThreadPool to download stuff in-parallel.

I definitely recommend taking the @gdrive_retry wrapper from DVC, so that it keeps running it even if you hit rate limits.

Please, let me know if that is enough to start :)

**Comment by pcseanmckay** [comment]
Thanks.  That should help.
